@echo off
title TYQ BOOT
echo TYQ BOOT...
echo [1/3] Speicher reservieren...
start "" /min cmd /c "python -m http.server 8080"
echo [2/3] Warte auf RAM & Server...
timeout /t 2 >nul
echo [3/3] KNOOPPIX + CHROMIUM START...
start "" http://localhost:8080/TYQ.html
echo TYQ SYSTEM: ONLINE
